- README.mkd
I left the coverage and travis ci links for now, they are still pointing to discogs accounts. I suggest we fix this in another PR when we have our own.
> README: replace deprecation warning with contributing notes

- discogs_client/models.py
- discogs_client/tests/res/users/example/collection/folders.json
- discogs_client/tests/res/users/example/collection/folders/0/releases_page=1&per_page=50.json
- discogs_client/tests/test_models.py
This one is also in use in [DiscoDOS](https://github.com/joj0/discodos) already since Jan 2019 and seems to be working well, at least for my needs. It's implementing this: https://www.discogs.com/developers#page:user-collection,header:user-collection-add-to-collection-folder
I just now found out that @frinkelpi implemented this back in 2017 already: https://github.com/frinkelpi/discogs_client/commit/cf11e86cb1ba849a395cb877d0c21015b0891513
It's pretty similar but I am not sure what the first line in his add method does and if it might be useful or even essential to add to my PR here. Tell me what you think! Thanks!
> add a release to a CollectionFolder

- README.mkd
Hi,
* I removed the issue link - it redirects to pull-request page. Obviously our repo doesn't support issues - I guess that's because we are a fork of discogs_client.
* headline change to python3-discogs-client, to represent our upstream name more prominently.
* add notes on documentation - This README currently is all we got - no issues possible, hence we point to the API forum.
> README: refine introductional text

- README.mkd
The `README` had out of date instructions to install the original package, this PR updates it so it points to this repos package
> Updated README to reflect new pypi package name

- .gitignore
- .travis.yml
- discogs_client/__init__.py
- discogs_client/client.py
- discogs_client/exceptions.py
- discogs_client/fetchers.py
- discogs_client/models.py
- discogs_client/tests/test_core.py
- discogs_client/tests/test_fetchers.py
- discogs_client/tests/test_models.py
- discogs_client/tests/test_utils.py
- discogs_client/utils.py
- requirements.txt
- setup.py
i took the time to remove the Python 2 specific code. also i think it's easier to maintain only currently supported Python versions. there's still a lot of opportunities to improve the code and i hope to have the time to contribute more.
> Refactors code for currently supported Python 3.6 to 3.9

- .gitignore
- setup.py
I realised on the last commit to master we didn't bump the version. It was a big change and I think we should. I've pushed the [latest to PyPi](https://pypi.org/project/python3-discogs-client/).
> Version bump

- setup.py
- As pointed out by @JOJ0 our 'Development Status' [on PyPI](https://pypi.org/project/python3-discogs-client/) is '7 - Inactive'
- This changes that to 'Development Status :: 5 - Production/Stable' 
- Once this is merged I'll upload it to PyPI so that it updates there
> Change Package Development status

- .github/workflows/discogs_client-build.yml
- I have realised from [PR 18](https://github.com/joalla/discogs_client/pull/18) that there should be more triggers to build on changes to PR. Hopefully this achieves that
- Used [this article](https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-do-workflows-trigger-on-pull_request) for reference
- Side effect is mutiple work flows run for each trigger, but I think that is ok. From the article below:
> One thing to note is that when you configure your pull_request workflow to be triggered on labeled or unlabeled and you add/remove multiple labels at the same time, the event of each label will trigger its own workflow run. It also works the same way for assigned/unassigned and review_requested/review_request_removed.
> More triggers to build on changes to PR 

- discogs_client/__init__.py
- discogs_client/tests/test_utils.py
- discogs_client/utils.py
also adds more imports to __init__.py
I tried to collect all strings I could find in the docs, there was three special conditions that the media condition does not accept but the sleeve condition does, `Generic`, `Not Graded` and `No Cover`
> Enums for condition, status and sort(by/order)

- README.mkd
Very minor change, but it always bugged me that some of the code snippets in the README used the python syntax hinter and some did not 😄 I also removed the `u'...'` prefix as unicode is default in python 3, this is left over from the python 2 days.
> Update README python tag to code snippets for syntax highlighting

- .github/workflows/release-check.yml
As a first step of automating our release process, this is just a simple comparison of version in setup.py and the latest (release) tag in the repo.
* Triggers on all release related actions (create, publish, edit, ....) except the unpublish action.
* Triggers when pushing a version tag (v...)
* Gets version from setup.py and latest git tag into the workflow environment
* Compares them and exits accordingly
I tested this in my fork, it seems to run stable, doesn't actually block anything and it is independent of our "build and test" workflow.
> Release version check gh-actions workflow

- discogs_client/models.py
- discogs_client/tests/res/marketplace/stats/1.json
- discogs_client/tests/test_models.py
I have extended the Python module with the `/marketplace/stats/{release_id}{?curr_abbr}` API endpoint. This endpoint exposes some Marketplace pricing information about a release. More information about this endpoint [here](https://www.discogs.com/developers#page:marketplace,header:marketplace-release-statistics).
> Add MarketplaceStats API endpoint

- discogs_client/models.py
- discogs_client/tests/res/users/example/collection/value.json
- discogs_client/tests/test_models.py
- As per request in the discussions [here](https://github.com/joalla/discogs_client/discussions/54#discussion-3371600), we haven't included the ability to fetch a user's collection value ([this endpoint](https://www.discogs.com/developers#page:user-collection,header:user-collection-collection-value))
- Unfortunately it seems like the API is limited to the fact it will give us the 'All' folders value, and not individual folder values
- Also it is set in the currency that your profile is in, it can be changed through the UI
> Added a user's Collection Value

- discogs_client/__init__.py
Fixing `__version__` shouldn't hurt, removing `__version_info__` entirely is a proposal. Tell me what you think @AnssiAhola and @alifhughes.
Some details in the commit message.
> Fix __version__ and get rid of __version_info__

- discogs_client/models.py
I added [this](https://www.discogs.com/developers/#page:marketplace,header:marketplace-price-suggestions) API point that was missing as was pointed out in the discussion #68 
Also added `year` property that was missing from the `Master` class. #67 [comment](https://github.com/joalla/discogs_client/discussions/67#discussioncomment-1791730)
I think this fix is so small that it can be clumped with the new API. What do you think @JOJ0 or @alifhughes ?
This still needs documentation for the new API point. I'll come back to that at some point.
Also any feedback is appreciated 😄
> Price suggestions

- docs/source/fetching_data.md
Here are potential docs for the new remove_release.  I made two changes, renaming the page to 'Managing Release and Collection data' and then added the code example from PR #88 as documentation.
Let me know if you want any changes made, I'm open to feedback.
Paul
> Update Docs: Add remove_release docs 

- discogs_client/models.py
WIP
Implements [this API point](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-items-by-release) as requested by @raratiru in #90
closes #90 
@JOJ0 @alifhughes If either of you could tell me what you think
Usage
```python
release_instances = me.collection_items(22155985)
for instance in release_instances:
print(instance) 
```
Once you have the instance you can get the collection folder it belong to and delete it (or do whatever)
```python
folder = me.collection_folders[instance.folder_id]
folder.remove_release(instance)
```
Not the most elegant but thats how the discogs api is sometimes :woman_shrugging:
> add method to fetch users collection items by release

- .github/workflows/discogs_client-build.yml
- requirements.txt
- sphinx_requirements.txt
Since recently we realized that our requirements.txt is wrong anyway (https://github.com/joalla/discogs_client/pull/99), I propse we kick it out. Regular installs from git use the deps provided in setup.py anway.
Users/devs who want to add to our docs should then be advised to simply install additional requirements from the simplified sphinx_requirements.txt file.
Also this PR should address the security vulnerabilites detected by dependabot: https://github.com/joalla/discogs_client/security/dependabot
> Fix dependency handling

- docs/source/conf.py
- docs/source/fetching_data.md
This PR:
- Documents the collection_items method introduced in PR#91.
- Adds a new chapter on how to use the fetch() method of an object.
- Applies fixes and additions to the Collection Data chapter in general.
This should build correctly, but I'm getting an error trying to do `make html` when building in a new environment.  Submitting the PR just in case someone does want to test and see if it builds.
I tested the methods and used the text written by AnssiAhola in the discussions to update the docs.  Any feedback on the docs is welcome.
Paul
Here's my error in a 3.9 venv: 
```
make html …
```
> Add docs for collection_items and fetch methods

- .github/workflows/discogs_client-build.yml
Tests for python 3.10 fail if using `nose`.
This is because nose is no longer maintained and uses `collection.Callable` which was [removed in 3.10](https://docs.python.org/3/whatsnew/3.10.html#removed)
Switched to using `unittest` which works fine.
Might be wise to remove the whole dependency to `nose`
Even thought the tests pass with 3.10, I don't think that's a guarantee that the client works in 3.10 completely without issues
> Add python 3.10 to github actions

- discogs_client/models.py
Adds community related fields from [GET Release API](https://www.discogs.com/developers#page:database,header:database-release-get)
closes #104
Usage
```python
release = client.release(15343679)
community_details = release.community
print(community_details)
>>> <CommunityDetails want/have: 34/74>
print (community_details.rating)
>>> <Rating avg: 4.5>
print(community_details.want)
>>> 34
print(community_details.have)
>>> 74
print(community_details.status)
>>> Accepted
print(community_details.data_quality)
>>> Needs Vote
print(community_details.contributors)
>>> [<User 1053297 'ManikRecs'>, <User 1241908 'neurosis76'>, <User 8867757 'silyn1'>, <User 3410038 'evasstra'>]
print(community_details.submitter)
>>> <User 1053297 'ManikRecs'>
```
> Add community details to Release

- discogs_client/models.py
To support a feature request in beetbox/beets: https://github.com/beetbox/beets/issues/4401#top, laying out this information via the client might help.
> Add attribute artists_sort to Release class

- discogs_client/models.py
- sphinx_requirements.txt
document it via autodoc autoattribute (#:).
Also fixes/unclutters all the other (child)classes in models.py by adding empty autoattribute comments.
> Add join attribute to Artist class and

- discogs_client/client.py
- discogs_client/fetchers.py
- discogs_client/tests/test_core.py
- docs/source/quickstart.md
Adds (optional) request timeout to the client as requested by @aw-was-here in #120 
Adds properties `connect_timeout` and `read_timeout` to base class `Fetcher`
Will use those properties and pass them to [`requests.request`](https://requests.readthedocs.io/en/latest/api/#requests.request) function as a tuple
These new properties are `None` by default as to not "break" existing apps etc.
Note. They are also None by default if not provided to the `requests.request` function [see link](https://requests.readthedocs.io/en/latest/user/advanced/#timeouts), kind of surprised this hasnt come up sooner :smile:
Usage:
```python
client = Client(my_client_name,user_token=my_token)
client.set_timeout(read=0.5)
user = client.user("MrJuusto")
for folder in user.collection_folders:
for release in …
```
> Add timeout to requests

- README.mkd
- docs/source/listing.md
In regards to **Marketplace Listings** - there are examples for Create, Update and Delete but not Read.
I will admit that this is something that confused me at first, so I wanted to add examples for others who maybe trying to do the same.
Pull request to update the README and docs with examples of how you can read and get listings from a user's inventory without authenticating as said user.
> Edit docs - Add section with example of getting a user's inventory

- .readthedocs.yaml
- docs/source/conf.py
- docs/source/writing_docs.md
- setup.py
- sphinx_requirements.txt
Fixes #136 
Add .readthedocs.yaml to fix rtd-builds and add docs requirements (replacing sphinx_requirements.txt) via extras section in setup.py.
This ignores our Jinja2 version fixation! Let's see if that works!
Also some wording changes in our "Writing docs section".
In enabled this PR's branch to review the changes and the succesful build: https://python3-discogs-client.readthedocs.io/en/fix_readthedocs/writing_docs.html
Build on RTD seems to be fine. Sphinx autodoc worked as well (that was IIRC the reason we had Jinja2 fixated to a specific version in the now deleted sphinx_requirements.txt.)
> Fix readthedocs builds, update copyright year & Writing Docs page

- .github/workflows/discogs_client-build.yml
- .github/workflows/release.yaml
some GitHub actions version upgrades. Not all deprectations fixed, but some.
> Fix gh-actions checkout action version deprecation

- .github/workflows/discogs_client-build.yml
- discogs_client/models.py
- discogs_client/tests/test_models.py
- docs/source/conf.py
- docs/source/fetching_data.md
> Move release between folders / Remove from all folders
